function Instruct = ShowInstruct(instNb, startCount, subtract, trialTout)
    
    instNb = num2str(instNb); % not to confound with 1/true or 0/false
       
%     ['\bf ', str{1}, ' \rm']
    switch instNb
        case '1'
            Instruct = ['======================== EPREUVE MENTALE ========================'];

        case 'C'
            Instruct = ['======================== ENTRAINEMENT ========================'];

        case '2'
            Instruct = ['INSTRUCTIONS CALCUL MENTAL: ', newline, newline...
                'Vous allez effectuer une tache de calcul mental.', newline, ...
                sprintf('Prenez le chiffre %d et soustrayez %.d, puis soustrayez encore %.d, etc.', startCount, subtract, subtract), newline,...
                sprintf('A chaque fois, vous n''aurez que %.1f secondes pour repondre.', trialTout), newline, newline, newline, ...
                'Il est donc important que vous soyez rapide et precis, puisque', newline, ...
                sprintf(' s''il y a une erreur, vous devrez recommencer a %d.', startCount),newline,newline,newline,newline, ...
                'La tache va bientot commencer... '];

        case '3'
            Instruct = ['INSTRUCTIONS GENERALES : ', newline, newline, ...
                'Pour les prochaines 28 minutes, vous devrez realiser (ordre indefini):', newline, newline, newline, ... 
                '1 tache d''effort mental', newline,...
                '2 periodes de repos', newline, newline, newline, ...
                'Au moment venu, des instructions seront diffusees a l''ecran pour', newline, ...
                'vous guider tout au long de l''epreuve. ', newline, newline, newline, newline...
                'Appuyez sur une touche pour continuer >>> '];

        case '4'
            Instruct = ['IMPORTANT : ', newline, newline, ...
                'Vous devrez au maximum rester calme et le plus immobile possible.', newline,...
                '(Les mouvements et la parole genent les enregistrements)', newline, newline,...
                'Si vous avez un probleme, levez la main pour', newline, ...
                'interagir avec l''experimentateur.rice', newline, newline, newline, newline, ...
                'Appuyez sur une touche pour continuer >>> '];

        case '5'
             Instruct = ['QUESTIONS : ', newline, newline, ...
                 'Avant de commencer, avez-vous des questions?', newline,...
                 'Si oui, levez la main.', newline, newline, newline, newline,...
                 'Appuyez sur une touche pour passer à l''entrainement', newline, ...
                 'de la tache mentale (duree : 30 secondes) >>> ']; 

        case '6'
            Instruct = ['INSTRUCTIONS : ', newline, newline, ...
                'Reposez-vous pendant quelques minutes.', newline, ...
                'Vous pouvez fermer les yeux si vous le souhaitez.', newline, newline,...
                'Un signal musical pour avertira que la', newline,...
                'periode est finie et des instructions', newline,...
                'seront a nouveau presentees a l''écran.' ];

        case '7'
            Instruct = ['======================== PERIODE DE REPOS ========================'];

        case '8'
            Instruct = ['===================== DIFFUSION DU BRUIT ====================='];

         case '10'
            Instruct = ['INSTRUCTIONS:', newline, newline, ...
                'Un bruit fort va être diffusé via les haut-parleurs',...
                ' pendant quelques minutes.'];
        case '9'
            Instruct = ['===================== EPREUVE TERMINEE =====================', ...
                newline, newline, newline, ...
                'Merci pour votre participation !'];
        
        case '11'
            Instruct = ['INSTRUCTIONS GENERALES : ', newline, newline, ...
                'Pour les prochaines 28 minutes, vous devrez realiser (ordre indefini):', newline, newline, newline, ... 
                '1 tâche d''effort mental', newline,...
                '1 tâche d''écoute d''un bruit fort', newline,...
                '2 periodes de repos', newline, newline, newline, ...
                'Au moment venu, des instructions seront diffusees a l''ecran pour', newline, ...
                'vous guider tout au long de l''epreuve. ', newline, newline, newline, newline...
                'Appuyez sur une touche pour continuer >>> '];

    end
        
end
