function Instruct = ShowInstruct(lang, instNb, startCount, subtract, trialTout)
    
    % TODO: Validate text of long instruction + translate them

    instNb = num2str(instNb); % not to confound with 1/true or 0/false
       
%     ['\bf ', str{1}, ' \rm']
    switch instNb
        case '1'
            if strcmpi(lang, 'fr')
                Instruct = '======================== EPREUVE MENTALE ========================';
            elseif strcmpi(lang, 'en')
                Instruct = '======================== MENTAL TASK ========================';
            end

        case 'C'
            if strcmpi(lang, 'fr')
                Instruct = '======================== ENTRAINEMENT ========================';
            elseif strcmpi(lang, 'en')
                Instruct = '======================== TRAINING ========================';
            end

        case '2'
            if strcmpi(lang, 'fr')
                Instruct = sprintf(['INSTRUCTIONS CALCUL MENTAL:\n\nVous allez effectuer une ' ...
                                    'tache de calcul mental.\nPrenez le chiffre %d et ' ...
                                    'soustrayez-y %.d. Entrez le nombre obtenu à l''aide du ', ...
                                    'clavier, puis appuyez sur "ENTRER". Continuez de soustraire', ...
                                    ' %.d du nombre obtenu précédemment encore et encore.\nLes', ...
                                    ' résultats validés ne seront pas réaffichés après chaque ', ...
                                    '"ENTRER". \n\n\n À chaque fois, vous n''aurez que %.1f secondes pour' ...
                                    ' repondre.\n\n\nIl est donc important que vous soyez ', ...
                                    'rapide et precis, puisque\ns''il y a une erreur, vous ', ...
                                    'devrez recommencer au début.\n\n\n\nLa tâche va bientot ', ...
                                    'commencer...'], startCount, subtract, subtract, trialTout, ...
                                    startCount);
%                 Instruct = sprintf(['INSTRUCTIONS CALCUL MENTAL:\n\nVous allez effectuer une ' ...
%                                     'tache de calcul mental.\nPrenez le chiffre %d et ' ...
%                                     'soustrayez %.d, puis soustrayez encore %.d, etc.\nA ' ...
%                                     'chaque fois, vous n''aurez que %.1f secondes pour ' ...
%                                     'repondre.\n\n\nIl est donc important que vous soyez ' ...
%                                     'rapide et precis, puisque\ns''il y a une erreur, vous ' ...
%                                     'devrez recommencer a %d.\n\n\n\nLa tache va bientot' ...
%                                     ' commencer...'], startCount, subtract, subtract, ...
%                                     trialTout, startCount);
%             elseif strcmpi(lang, 'en')
%                 Instruct = sprintf(['INSTRUCTIONS CALCUL MENTAL:\n\nVous allez effectuer une ' ...
%                                     'tache de calcul mental.\nPrenez le chiffre %d et ' ...
%                                     'soustrayez %.d, puis soustrayez encore %.d, etc.\nA ' ...
%                                     'chaque fois, vous n''aurez que %.1f secondes pour ' ...
%                                     'repondre.\n\n\nIl est donc important que vous soyez ' ...
%                                     'rapide et precis, puisque\ns''il y a une erreur, vous ' ...
%                                     'devrez recommencer a %d.\n\n\n\nLa tache va bientot' ...
%                                     ' commencer...'], startCount, subtract, subtract, ...
%                                     trialTout, startCount);
            elseif strcmpi(lang, 'en')
                Instruct = sprintf(['INSTRUCTIONS CALCUL MENTAL:\n\nVous allez effectuer une ' ...
                                    'tache de calcul mental.\nPrenez le chiffre %d et ' ...
                                    'soustrayez %.d, puis soustrayez encore %.d, etc.\nA ' ...
                                    'chaque fois, vous n''aurez que %.1f secondes pour ' ...
                                    'repondre.\n\n\nIl est donc important que vous soyez ' ...
                                    'rapide et precis, puisque\ns''il y a une erreur, vous ' ...
                                    'devrez recommencer a %d.\n\n\n\nLa tache va bientot' ...
                                    ' commencer...'], startCount, subtract, subtract, ...
                                    trialTout, startCount);
            end

        case '3'
            if strcmpi(lang, 'fr')
                Instruct = sprintf(['INSTRUCTIONS GENERALES :\n\nPour les prochaines 28 ', ...
                                    'minutes, vous devrez realiser (ordre indefini):\n\n\n', ...
                                    '1 tache d''effort mental\n2 periodes de repos\n\n\nAu ',...
                                    'moment venu, des instructions seront diffusees a l''ecran', ...
                                    ' pour\nvous guider tout au long de l''epreuve.\n\n\n\n', ...
                                    'Appuyez sur "SPACE" pour continuer >>> ']);
            elseif strcmpi(lang, 'en')
                Instruct = sprintf(['INSTRUCTIONS GENERALES :\n\nPour les prochaines 28 ', ...
                                    'minutes, vous devrez realiser (ordre indefini):\n\n\n', ...
                                    '1 tache d''effort mental\n2 periodes de repos\n\n\nAu ',...
                                    'moment venu, des instructions seront diffusees a l''ecran', ...
                                    ' pour\nvous guider tout au long de l''epreuve.\n\n\n\n', ...
                                    'Appuyez sur "SPACE" pour continuer >>> ']);
            end

        case '4'
            if strcmpi(lang, 'fr')
                Instruct = sprintf(['IMPORTANT :\n\nVous devrez rester calme au maximum et le ', ...
                                    'plus immobile possible.\n(Les mouvements et la parole ', ...
                                    'genent les enregistrements)\n\nSi vous avez un probleme, ', ...
                                    'levez la main pour\ninteragir avec l''experimentateur/rice', ...
                                    '\n\n\n\nAppuyez sur "SPACE" pour continuer >>>']);
            elseif strcmpi(lang, 'en')
                Instruct = sprintf(['IMPORTANT :\n\nVous devrez rester calme au maximum et le ', ...
                                    'plus immobile possible.\n(Les mouvements et la parole ', ...
                                    'genent les enregistrements)\n\nSi vous avez un probleme, ', ...
                                    'levez la main pour\ninteragir avec l''experimentateur/rice', ...
                                    '\n\n\n\nAppuyez sur "SPACE" pour continuer >>>']);
            end

        case '5'
             if strcmpi(lang, 'fr')
                Instruct = sprintf(['QUESTIONS :\n\nAvant de commencer, avez-vous des ', ...
                                    'questions?\nSi oui, levez la main.\n\n\n\nAppuyez sur ', ...
                                    '"SPACE" pour passer à l''entrainement\nde la tache ', ...
                                    'mentale (duree : 30 secondes) >>> ']);
            elseif strcmpi(lang, 'en')
                Instruct = sprintf(['QUESTIONS :\n\nAvant de commencer, avez-vous des ', ...
                                    'questions?\nSi oui, levez la main.\n\n\n\nAppuyez sur ', ...
                                    '"SPACE" pour passer à l''entrainement\nde la tache ', ...
                                    'mentale (duree : 30 secondes) >>> ']);
            end

        case '6'
            if strcmpi(lang, 'fr')
                Instruct = sprintf(['INSTRUCTIONS :\n\nReposez-vous pendant minutes.\nVous ', ...
                                    'pouvez fermer les yeux si vous le souhaitez.\n\n Un ', ...
                                    'signal musical pour avertira que la\nperiode est finie et', ...
                                    ' des instructions\nseront a nouveau presentees a l''écran.']);
            elseif strcmpi(lang, 'en')
                Instruct = sprintf(['INSTRUCTIONS :\n\nReposez-vous pendant minutes.\nVous ', ...
                                    'pouvez fermer les yeux si vous le souhaitez.\n\n Un ', ...
                                    'signal musical pour avertira que la\nperiode est finie et', ...
                                    ' des instructions\nseront a nouveau presentees a l''écran.']);
            end

        case '7'
            if strcmpi(lang, 'fr')
                Instruct = '======================== PERIODE DE REPOS ========================';
            elseif strcmpi(lang, 'en')
                Instruct = '======================== REST PERIOD ========================';                
            end

        case '8'
            if strcmpi(lang, 'fr')
                Instruct = ['===================== DIFFUSION DU BRUIT ====================='];
            elseif strcmpi(lang, 'en')
                Instruct = ['===================== BROADCASTING NOISE ====================='];
            end

         case '10'
            if strcmpi(lang, 'fr')
                Instruct = sprintf(['INSTRUCTIONS:\n\nUn bruit fort va petre diffusé via les ', ...
                                    'haut-parleurs pendant quelques minutes.']);
            elseif strcmpi(lang, 'en')
                Instruct = sprintf(['INSTRUCTIONS:\n\nUn bruit fort va être diffusé via les ', ...
                                    'haut-parleurs pendant quelques minutes.']);
            end
        case '9'
            if strcmpi(lang, 'fr')
                Instruct = sprintf(['===================== EPREUVE TERMINEE %s\n\n\nMerci pour', ...
                                    ' votre participation !'], '=====================');
            elseif strcmpi(lang, 'en')
                Instruct = sprintf(['===================== TASK COMPLETED %s\n\n\nThank you ', ...
                                    'for participating !'], '=====================');
            end
        
        case '11'
            if strcmpi(lang, 'fr')
                Instruct = sprintf(['INSTRUCTIONS GENERALES :\n\nPour les prochaines 28 ', ...
                                    'minutes, vous devrez realiser (ordre indefini):\n\n\n', ... 
                                    '1 tâche d''effort mental\n1 tâche d''écoute d''un bruit ',...
                                    'fort\n2 periodes de repos\n\n\nAu moment venu, des ',...
                                    'instructions seront diffusees a l''ecran pour\nvous ', ...
                                    'guider tout au long de l''epreuve.\n\n\n\nAppuyez sur une', ...
                                    ' touche pour continuer >>> ']);
            elseif strcmpi(lang, 'en')
                Instruct = sprintf(['INSTRUCTIONS GENERALES :\n\nPour les prochaines 28 ', ...
                                    'minutes, vous devrez realiser (ordre indefini):\n\n\n', ...
                                    '1 tâche d''effort mental\n1 tâche d''écoute d''un bruit ',...
                                    'fort\n2 periodes de repos\n\n\nAu moment venu, des ',...
                                    'instructions seront diffusees a l''ecran pour\nvous ', ...
                                    'guider tout au long de l''epreuve.\n\n\n\nAppuyez sur une', ...
                                    ' touche pour continuer >>> ']);
            end

    end
        
end
